version: "3.2"
services:
  db:
    restart: always
    image: mariadb:5.5
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_ROOT_HOST=%
      - MYSQL_DATABASE=EloTracker
      - MYSQL_USER=EloTracker
      - MYSQL_PASSWORD=123
      - MYSQL_ROOT_PASSWORD=123
    ports:
      - "3302:3306"
    networks:
      - db-net

  elotracker-app:
    container_name: EloTracker-app
    build:
      context: .
    command : bash -c "python manage.py migrate &&
                      python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY=')u#-td@r@80@3m0g9b1u#h=xsu2i&n&fck0!%ay9e)lf4sdb4b'
      - ALLOWED_HOSTS=127.0.0.1, localhost
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - db-net
      
networks:
  db-net:
    driver: bridge